# Generated by Django 3.2.4 on 2021-06-10 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_forgotpasswordtoken_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forgot_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verificationtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
